# Generated by Django 5.0.6 on 2024-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('service', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
