# Generated by Django 5.0.6 on 2024-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_signupinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
